# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"
    numpy: "1.21"
    scipy: "1.11"

sphinx:
  configuration: docs/conf.py